### ISSUE TITLE
XBMC Plugin - Crashing, when tcp port 9090 not available.

### ISSUE THREAD

**Issue by gmccandless** [opensourceautomation/Open-Source-Automation#191]
I have built up a network of Raspberry PI's all running Rasbmc. As the build is now in a very stable and usable state I thought I'd start using the xbmc plugin to track which rooms are occupied in a simple manner. So using the plugin I track when when xbmc is playing and stopped, therefore can set a room to occupied or vacated. I have something a little better in mind but for now this approach works well.

I've noticed the following in the logs;

XBMC plugin has fatally crashed. ERROR: 
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 192.168.100.55:9090
at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at XBMCRPC.Client.<StartNotificationListener>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__1(Object state)
at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

This can happen when tcp port 9090 closes, either because one of the RPI's has rebooted or closes unexpected due to some kind of crash on the RPi. Not really a big problem, however the xbmc plugin doesn't recover until I complete a restart of the plugin.

Thanks in advance.

Cheers

Garry

**Comment by VaughnRupp** [comment]
It looks like everything is error trapped pretty well, this is such an old issue, I wonder if it has been fixed.   If anyone runs this plugin, and has had crash issues or can duplicate an issue with a bad port number, it would really help.    Else I will eventually get an XBMC system set up again...

**Comment by VaughnRupp** [comment]
I am just closing this issue per previous comment and lack of response.
